### PR TITLE
Fix response log obfuscation

### LINKED ISSUE #63: Log obfuscation is not working for requests response
Currently, requests logs are not obfuscated for any of the responses.

This was caused by this [change](https://github.com/uphold/request-logger/commit/d83a846dfa2fef87f3c870ab2abbe31a0d5f0f1e) and this [bump](https://github.com/ruimarinho/bitcoin-core/commit/c9eb6584a85c66cb1cb71453498ddc80ad3b2759).

### PR DESCRIPTION
**Pull request by pedrobranco**
Closes #63.

### CODE REVIEW

File: src/logging/request-obfuscator.js [hunk 1]
```diff
@@ -49,17 +49,19 @@ function obfuscateResponse(request, instance) {
     return;
   }
 
+  request.body = JSON.parse(request.body);
```
Comment (ruimarinho) [inline src/logging/request-obfuscator.js]: @pedrobranco shouldn't we be keeping the same string as before?

Comment (pedrobranco) [reply src/logging/request-obfuscator.js]: Fixed.

Comment (ruimarinho) [reply src/logging/request-obfuscator.js]: I suggest passing the parsed body as an argument instead of mutating `request.body` here. I would then stringify the resulting (mutated) `body` object at the end of the method.

Comment (pedrobranco) [reply src/logging/request-obfuscator.js]: Oh sure.
